export type EventStatus = 'planning' | 'confirmed' | 'in_progress' | 'completed' | 'cancelled';

export interface PizzaEvent {
  id: string;
  name: string;
  date: string;
  endDate?: string;
  time?: string;
  duration?: string;
  location: string;
  outOfCity?: boolean;
  phone?: string;
  guestCount: number;
  status: EventStatus;
  budget: number;
  menu: string[];
  notes: string;
  responsibleEmployeeId?: string;
  staffCount?: number;
  selectedEmployeeIds?: string[];
  paymentProofName?: string;
  contractPdfName?: string;
  createdBy?: string;
  createdAt: string;
  unit?: string;
  source?: string;
  celebration?: string;
  teamArrivalTime?: string;
  city?: string;
  guestsAdult?: number;
  guestsTeen?: number;
  guestsChild?: number;
  travelCost?: number;
  teamPizzaiolo?: string;
  teamHelper?: string;
  teamGarcon?: string;
  extrasLoucas?: number;
  extrasBebidas?: number;
  finalValue?: number;
  paymentMethod?: string;
  locationImageName?: string;
  locationImageData?: string;
  paymentProofData?: string;
  contractPdfData?: string;
}
