import { z } from 'zod';

export const createFinanceSchema = z.object({
  eventId: z.string().optional().default(''),
  type: z.enum(['revenue', 'cost']),
  category: z.string().min(1, 'Categoria obrigatória').trim(),
  description: z.string().optional().default(''),
  amount: z.number().positive('Valor deve ser positivo'),
  date: z.string().regex(/^\d{4}-\d{2}-\d{2}$/, 'Data deve ser YYYY-MM-DD'),
  status: z.enum(['pending', 'paid', 'received']).optional().default('pending'),
  autoEventBudget: z.boolean().optional().default(false),
  origin: z.enum(['event', 'manual', 'factory_order', 'bank_import']).optional(),
  kind: z.enum(['balance', 'deposit', 'travel', 'commission', 'expense', 'manual']).optional(),
  employeeId: z.string().optional(),
  paymentMethod: z.string().optional(),
  dueDate: z.string().regex(/^\d{4}-\d{2}-\d{2}$/).optional(),
  settledAt: z.string().optional(),
  settlementStatus: z.enum(['open', 'partial', 'settled', 'cancelled']).optional(),
  automatic: z.boolean().optional(),
  reversedAt: z.string().optional(),
  reversedBy: z.string().optional(),
  reversalReason: z.string().optional(),
  installmentGroupId: z.string().optional(),
  installmentNumber: z.number().optional(),
  installmentTotal: z.number().optional(),
  recurrenceId: z.string().optional(),
  recurrenceFrequency: z.enum(['daily', 'weekly', 'monthly', 'yearly']).optional(),
  recurrenceEndDate: z.string().optional(),
  recurrenceInterval: z.number().int().min(1).max(365).optional(),
  recurrenceTotal: z.number().int().min(1).max(366).optional(),
  externalId: z.string().max(300).optional(),
  importBatchId: z.string().max(100).optional(),
  bankAccount: z.string().max(200).optional(),
  bankStatementBalance: z.number().finite().optional(),
});

export const updateFinanceSchema = createFinanceSchema.partial();
